version: "3.8"

services:
    program:
        build: 
            context: .
            args: 
                RUST_APP: ${RUST_APP} # use the vars from the .env file
        ports:
            - ${PORT}:${PORT} # use the vars from the .env file
        volumes:
            - pastebin:/usr/src/rust_program
volumes:
    pastebin: